// Generated by CoffeeScript 1.9.3
(function() {
  $(document).ready(function() {
    var init_map;
    $('.more-info').click(function() {
      $('html, body').animate({
        scrollTop: $($(this).attr('href')).offset().top
      }, 500);
      return false;
    });
    $('#menu').onePageNav({
      currentClass: "active",
      changeHash: false,
      scrollThreshold: 0.5,
      scrollSpeed: 750,
      filter: '',
      easing: 'swing'
    });
    $('#welcome').vegas({
      slides: [
        {
          src: 'app/img/hydraulik.jpg'
        }, {
          src: 'app/img/elektryk.jpg'
        }, {
          src: 'app/img/spawanie.jpg'
        }, {
          src: 'app/img/slusarz.jpg'
        }
      ],
      overlay: true
    });
    $('#vegas-next').click(function() {
      return $('#welcome').vegas('next');
    });
    $('#vegas-prev').click(function() {
      return $('#welcome').vegas('previous');
    });
    $('#contactForm').validate({
      rules: {
        name: {
          minlength: 2,
          required: true
        },
        email: {
          required: true,
          email: true
        },
        body: {
          minlength: 2,
          required: true
        }
      },
      highlight: function(element) {
        return $(element).closest('.control-group').removeClass('success').addClass('error');
      },
      success: function(element) {
        element.addClass('valid').text("Ok");
        return $(element).closest('.control-group').removeClass('error').addClass('success');
      },
      messages: {
        name: {
          required: "To pole jest wymagane",
          minlength: "Proszę wpisać co najmniej dwa znaki"
        },
        email: {
          required: "To pole jest wymagane",
          email: "Proszę wpisać poprawny adres email"
        },
        body: {
          required: "To pole jest wymagane",
          minlength: "Proszę wpisać co najmniej dwa znaki"
        }
      }
    });
    $(document).scroll(function() {
      if ($(this).scrollTop() > 0) {
        return $(".navbar-default").css('background-color', '#3E454C');
      } else {
        return $('.navbar-default').css('background-color', 'transparent');
      }
    });
    init_map = function() {
      var location, map, mapoptions, marker;
      location = new google.maps.LatLng(50.0646501, 19.9449799);
      mapoptions = {
        center: location,
        zoom: 10
      };
      marker = new google.maps.Marker({
        position: location,
        map: map,
        title: "Venice"
      });
      map = new google.maps.Map(document.getElementById("map"), mapoptions);
      return marker.setMap(map);
    };
    return google.maps.event.addDomListener(window, 'load', init_map);
  });

}).call(this);

//# sourceMappingURL=app.js.map
