// Generated by CoffeeScript 1.9.3
(function() {
  $(document).ready(function() {
    $('.more-info').click(function() {
      $('.main').moveDown();
      return false;
    });
    $('.contact').click(function() {
      $('.main').moveTo(6);
      return false;
    });
    $('.main').onepage_scroll({
      keyboard: true,
      loop: true
    });
    $('#welcome').vegas({
      slides: [
        {
          src: 'app/img/tool-384740_1280.jpg'
        }, {
          src: 'app/img/light-bulb.jpg'
        }, {
          src: 'app/img/tools-864983_1280.jpg'
        }, {
          src: 'app/img/keys.jpg'
        }
      ],
      overlay: true
    });
    $('#vegas-next').click(function() {
      return $('#welcome').vegas('next');
    });
    $('#vegas-prev').click(function() {
      return $('#welcome').vegas('previous');
    });
    return $('#contactForm').validate({
      rules: {
        name: {
          minlength: 2,
          required: true
        },
        email: {
          required: true,
          email: true
        },
        body: {
          minlength: 2,
          required: true
        }
      },
      highlight: function(element) {
        return $(element).closest('.control-group').removeClass('success').addClass('error');
      },
      success: function(element) {
        element.addClass('valid').text("Ok");
        return $(element).closest('.control-group').removeClass('error').addClass('success');
      },
      messages: {
        name: {
          required: "To pole jest wymagane",
          minlength: "Proszę wpisać co najmniej dwa znaki"
        },
        email: {
          required: "To pole jest wymagane",
          email: "Proszę wpisać poprawny adres email"
        },
        body: {
          required: "To pole jest wymagane",
          minlength: "Proszę wpisać co najmniej dwa znaki"
        }
      }
    });
  });

}).call(this);

//# sourceMappingURL=app.js.map
